Allow use of key attributes in assignableProperties
malomalo/viking pull request #70
Opened 2021-06-09 21:27 UTC by bemky

2021-06-10 14:45 UTC, malomalo commented on lib/viking/view.js
> +            }
```suggestion
            let attrs = {};
            
            // if attributes is not in assignableProperties it is assumed the user is using it
            if (!scanPrototypesFor(this.constructor, 'assignableProperties').flat().includes('attributes')) {
                Object.assign(attrs, result(this, 'attributes'));
            }
```

2021-06-10 14:49 UTC, malomalo requested changes

2021-06-10 14:49 UTC, malomalo commented on lib/viking/view.js
> +            }
Actually just skip the `each` where it assigns them to the element too because if it's in `assignableProperties` then it doesn't need to do the loop

2021-06-10 15:56 UTC, bemky commented
Still have to do `each` because of ability to set `id` and `className`.
https://github.com/malomalo/viking/blob/master/lib/viking/view.js#L142

2021-06-10 17:14 UTC, bemky commented
@malomalo added test, ready for rereview

2021-06-11 19:03 UTC, malomalo approved these changes

2021-06-11 19:57 UTC, merged